// src/auth/auth.ts
import { betterAuth } from "better-auth";
import { bearer, openAPI } from "better-auth/plugins";
import { normalizeOrigins } from "../config/cors.js";
import { env } from "../config/env.js";
import { pool } from "../db/pool.js";

const isProduction = env.NODE_ENV === "production";

/**
 * Better Auth instance. Routes are served under `/auth/*` by the Express app
 * (see app.ts); sessions, users and accounts live in the same Postgres as the
 * catalogue (migrations/002_auth.sql, generated by `npm run auth:schema`).
 *
 * Two ways for a client to hold a session:
 * - Cookies. Set by sign-up / sign-in; sent back with `credentials: "include"`.
 *   In production they are `SameSite=None; Secure`, which browsers accept only
 *   when the API and the site count as the same site (a custom domain with
 *   subdomains). Two different *.vercel.app hosts are different sites, and
 *   Safari drops the cookie there.
 * - Bearer tokens (the `bearer` plugin). Sign-in responses carry the session
 *   token in a `set-auth-token` header; send it back as
 *   `Authorization: Bearer <token>`. Works from any origin.
 */
export const auth = betterAuth({
  appName: "Zara-inspired storefront",
  baseURL: env.BETTER_AUTH_URL,
  basePath: "/auth",
  secret: env.BETTER_AUTH_SECRET,
  database: pool,

  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    maxPasswordLength: 128,
    // No mail provider yet: accounts work without verifying the address.
    requireEmailVerification: false,
  },

  session: {
    expiresIn: 60 * 60 * 24 * 30, // 30 days
    updateAge: 60 * 60 * 24, // refresh the expiry once a day of use
    // Serve repeat requests from a signed cookie for five minutes before
    // consulting the session table again.
    cookieCache: { enabled: true, maxAge: 60 * 5 },
  },

  // Origins allowed to call the auth routes from a browser: the CORS list,
  // `*` patterns included (Better Auth matches them itself).
  trustedOrigins: normalizeOrigins(env.FRONTEND_ORIGIN),

  rateLimit: {
    enabled: isProduction,
    // Serverless instances share nothing, so counts go to the database.
    storage: "database",
    window: 60,
    max: 60,
    customRules: {
      "/sign-in/email": { window: 60, max: 10 },
      "/sign-up/email": { window: 60, max: 10 },
    },
  },

  advanced: {
    useSecureCookies: isProduction,
    defaultCookieAttributes: isProduction ? { sameSite: "none", secure: true } : undefined,
    database: { generateId: "uuid" },
  },

  plugins: [
    bearer(),
    // Generated reference for every auth endpoint at GET /auth/reference.
    openAPI(),
  ],
});

export type Session = typeof auth.$Infer.Session;
export type User = Session["user"];
