import { Router } from "express";
import { auth } from "../../auth/auth.js";
import spec from "../../openapi.json" with { type: "json" };

/** The reference page: renders the OpenAPI document with Scalar, loaded from a CDN. */
const DOCS_HTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Storefront API</title>
</head>
<body>
  <div id="app"></div>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  <script>
    Scalar.createApiReference("#app", { url: "/openapi.json", theme: "default", hideModels: false });
  </script>
</body>
</html>`;

type PathItem = Record<string, { tags?: string[]; responses?: unknown } | undefined>;

/**
 * The hand-written spec (catalogue, /me) plus every auth route, generated by
 * Better Auth from its live configuration and mounted under /auth. Built once
 * per process.
 */
let merged: Promise<object> | undefined;
async function fullSpec(): Promise<object> {
  merged ??= (async () => {
    const authSpec = (await auth.api.generateOpenAPISchema()) as unknown as {
      paths: Record<string, PathItem>;
      components: { schemas: Record<string, unknown> };
    };
    const paths: Record<string, PathItem> = { ...(spec.paths as Record<string, PathItem>) };
    for (const [path, item] of Object.entries(authSpec.paths)) {
      const operations = structuredClone(item);
      for (const operation of Object.values(operations)) {
        if (operation && typeof operation === "object" && "responses" in operation) operation.tags = ["Auth"];
      }
      paths[`/auth${path}`] = operations;
    }
    return {
      ...spec,
      paths,
      components: {
        ...spec.components,
        // Better Auth's models (User, Session, ...) first; ours win on a name clash.
        schemas: { ...authSpec.components.schemas, ...spec.components.schemas },
      },
    };
  })();
  return merged;
}

export const docsRouter = Router();

// The base document is imported rather than read from disk so serverless
// bundlers ship it with the function.
docsRouter.get("/openapi.json", async (_req, res, next) => {
  try {
    res.json(await fullSpec());
  } catch (error) {
    next(error);
  }
});

docsRouter.get("/docs", (_req, res) => {
  res.type("html").send(DOCS_HTML);
});
