/**
 * Writes seeds/<NN_table>/<table>.sql from the storefront's static catalogue
 * (apps/web/lib/data), so the database starts with exactly what the mockup
 * shows: 3 sections, their categories, 266 products, one row per colour,
 * one variant per colour × size. Images are placehold.co placeholders.
 *
 *   npx tsx scripts/generate-catalog-seed.ts   (from apps/api)
 *
 * One folder per table, each file made of small INSERT statements (CHUNK rows) that
 * commit independently, so a slow or dropped connection only costs one chunk
 * and re-running resumes where it stopped (ON CONFLICT DO NOTHING throughout).
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { SECTIONS } from "../../web/lib/data/catalog.ts";
import { PRODUCTS } from "../../web/lib/data/products.ts";
import { luminance } from "../../web/lib/data/colors.ts";

const SEEDS = fileURLToPath(new URL("../seeds/", import.meta.url));
const CHUNK = 100;
const SEASON = "AW26";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
// E'' string so multi-line composition text stays readable in the file.
const qe = (s: string) => `E'${s.replace(/\\/g, "\\\\").replace(/'/g, "''").replace(/\n/g, "\\n")}'`;
const cents = (n: number) => Math.round(n * 100);
// The static data rounds compare-at to a x9.90 pattern, which for the cheapest
// sale item lands on the price itself; the schema requires strictly higher.
const compareAtCents = (price: number, compareAt: number | undefined) => {
  if (compareAt === undefined) return null;
  const c = cents(compareAt);
  return c > cents(price) ? c : cents(price) + 500;
};
const skuPart = (s: string) => s.toUpperCase().replace(/[^A-Z0-9]+/g, "");

/** Deterministic 0–12 from a string; ~1 in 8 sizes end up out of stock. */
function stock(key: string): number {
  let h = 2166136261;
  for (const ch of key) h = Math.imul(h ^ ch.charCodeAt(0), 16777619);
  const n = (h >>> 0) % 16;
  return n < 2 ? 0 : (n % 12) + 1;
}

function placeholder(hex: string, text: string): string {
  const bg = hex.replace("#", "");
  const fg = luminance(hex) > 0.5 ? "1a1a1a" : "f4f3f1";
  return `https://placehold.co/600x900/${bg}/${fg}?text=${encodeURIComponent(text).replace(/%20/g, "+")}`;
}

function chunked(header: string, rows: string[], conflict: string): string {
  const out: string[] = [];
  for (let i = 0; i < rows.length; i += CHUNK) {
    out.push(header, rows.slice(i, i + CHUNK).join(",\n"), `ON CONFLICT ${conflict} DO NOTHING;`, "");
  }
  return out.join("\n");
}

const files: Record<string, string> = {
  "01_categories/categories.sql": [
    "-- Generated by scripts/generate-catalog-seed.ts from apps/web/lib/data. Do not edit by hand.",
    "-- Sections are root categories; NEW IN / SPECIAL PRICES / BEST SELLERS are flags on products, not rows.",
    "",
    chunked(
      "INSERT INTO categories (slug, name, path, position) VALUES",
      SECTIONS.map((s, i) => `  (${q(s.slug)}, ${q(s.name)}, ${q(s.slug)}, ${i})`),
      "(path)",
    ),
    chunked(
      "INSERT INTO categories (parent_id, slug, name, path, position) VALUES",
      SECTIONS.flatMap((s) =>
        s.categories
          .filter((c) => !c.virtual)
          .map(
            (c, i) =>
              `  ((SELECT id FROM categories WHERE path = ${q(s.slug)}), ${q(c.slug)}, ${q(c.name)}, ${q(`${s.slug}/${c.slug}`)}, ${i})`,
          ),
      ),
      "(path)",
    ),
  ].join("\n"),

  "02_products/products.sql": [
    `-- Generated by scripts/generate-catalog-seed.ts. ${PRODUCTS.length} products in chunks of ${CHUNK}. Requires 01_categories.`,
    "",
    chunked(
      "INSERT INTO products (slug, name, ref, description, composition, section, category_id, price_cents, compare_at_cents, is_new, is_best_seller, season, status) VALUES",
      PRODUCTS.map(
        (p) =>
          `  (${q(p.slug)}, ${q(p.name)}, ${q(p.ref)}, ${q(p.description)}, ${qe(p.composition)}, ${q(p.section)}, (SELECT id FROM categories WHERE path = ${q(`${p.section}/${p.category}`)}), ${cents(p.price)}, ${compareAtCents(p.price, p.compareAt) ?? "NULL"}, ${p.isNew}, ${p.isBestSeller}, ${q(SEASON)}, 'live')`,
      ),
      "(slug)",
    ),
  ].join("\n"),

  "03_product_colours/product_colours.sql": [
    `-- Generated by scripts/generate-catalog-seed.ts. ${PRODUCTS.reduce((n, p) => n + p.colors.length, 0)} colours, two placeholder images each. Requires 02_products.`,
    "",
    chunked(
      "INSERT INTO product_colours (product_id, name, hex, images, position) VALUES",
      PRODUCTS.flatMap((p) =>
        p.colors.map((c, i) => {
          const images = [placeholder(c.hex, p.name), placeholder(c.hex, `${c.name} DETAIL`)];
          return `  ((SELECT id FROM products WHERE slug = ${q(p.slug)}), ${q(c.name)}, ${q(c.hex.toLowerCase())}, ${q(JSON.stringify(images))}::jsonb, ${i})`;
        }),
      ),
      "(product_id, name)",
    ),
  ].join("\n"),

  "04_variants/variants.sql": [
    `-- Generated by scripts/generate-catalog-seed.ts. ${PRODUCTS.reduce((n, p) => n + p.colors.length * p.sizes.length, 0)} variants (colour × size) with stock. Requires 03_product_colours.`,
    "",
    chunked(
      "INSERT INTO variants (colour_id, sku, size, stock_qty, position) VALUES",
      PRODUCTS.flatMap((p) =>
        p.colors.flatMap((c) =>
          p.sizes.map((size, i) => {
            const sku = `${skuPart(p.ref)}-${skuPart(c.name)}-${skuPart(size)}`;
            return `  ((SELECT c.id FROM product_colours c JOIN products p ON p.id = c.product_id WHERE p.slug = ${q(p.slug)} AND c.name = ${q(c.name)}), ${q(sku)}, ${q(size)}, ${stock(sku)}, ${i})`;
          }),
        ),
      ),
      "(sku)",
    ),
  ].join("\n"),
};

for (const [name, sql] of Object.entries(files)) {
  await mkdir(SEEDS + dirname(name), { recursive: true });
  await writeFile(SEEDS + name, sql);
  console.log(`wrote seeds/${name} (${Math.round(sql.length / 1024)} KB)`);
}
