-- Generated by scripts/generate-catalog-seed.ts from apps/web/lib/data. Do not edit by hand.
-- Sections are root categories; NEW IN / SPECIAL PRICES / BEST SELLERS are flags on products, not rows.

INSERT INTO categories (slug, name, path, position) VALUES
  ('woman', 'WOMAN', 'woman', 0),
  ('man', 'MAN', 'man', 1),
  ('kids', 'KIDS', 'kids', 2)
ON CONFLICT (path) DO NOTHING;

INSERT INTO categories (parent_id, slug, name, path, position) VALUES
  ((SELECT id FROM categories WHERE path = 'woman'), 'dresses', 'DRESSES', 'woman/dresses', 0),
  ((SELECT id FROM categories WHERE path = 'woman'), 'tops', 'TOPS', 'woman/tops', 1),
  ((SELECT id FROM categories WHERE path = 'woman'), 't-shirts', 'T-SHIRTS', 'woman/t-shirts', 2),
  ((SELECT id FROM categories WHERE path = 'woman'), 'shirts', 'SHIRTS', 'woman/shirts', 3),
  ((SELECT id FROM categories WHERE path = 'woman'), 'jackets', 'JACKETS', 'woman/jackets', 4),
  ((SELECT id FROM categories WHERE path = 'woman'), 'coats', 'COATS', 'woman/coats', 5),
  ((SELECT id FROM categories WHERE path = 'woman'), 'blazers', 'BLAZERS', 'woman/blazers', 6),
  ((SELECT id FROM categories WHERE path = 'woman'), 'knitwear', 'KNITWEAR', 'woman/knitwear', 7),
  ((SELECT id FROM categories WHERE path = 'woman'), 'trousers', 'TROUSERS', 'woman/trousers', 8),
  ((SELECT id FROM categories WHERE path = 'woman'), 'jeans', 'JEANS', 'woman/jeans', 9),
  ((SELECT id FROM categories WHERE path = 'woman'), 'skirts', 'SKIRTS', 'woman/skirts', 10),
  ((SELECT id FROM categories WHERE path = 'woman'), 'shoes', 'SHOES', 'woman/shoes', 11),
  ((SELECT id FROM categories WHERE path = 'woman'), 'bags', 'BAGS', 'woman/bags', 12),
  ((SELECT id FROM categories WHERE path = 'woman'), 'accessories', 'ACCESSORIES', 'woman/accessories', 13),
  ((SELECT id FROM categories WHERE path = 'woman'), 'perfumes', 'PERFUMES', 'woman/perfumes', 14),
  ((SELECT id FROM categories WHERE path = 'man'), 'jackets', 'JACKETS', 'man/jackets', 0),
  ((SELECT id FROM categories WHERE path = 'man'), 'coats', 'COATS', 'man/coats', 1),
  ((SELECT id FROM categories WHERE path = 'man'), 'blazers', 'BLAZERS', 'man/blazers', 2),
  ((SELECT id FROM categories WHERE path = 'man'), 'shirts', 'SHIRTS', 'man/shirts', 3),
  ((SELECT id FROM categories WHERE path = 'man'), 't-shirts', 'T-SHIRTS', 'man/t-shirts', 4),
  ((SELECT id FROM categories WHERE path = 'man'), 'sweatshirts', 'SWEATSHIRTS', 'man/sweatshirts', 5),
  ((SELECT id FROM categories WHERE path = 'man'), 'knitwear', 'KNITWEAR', 'man/knitwear', 6),
  ((SELECT id FROM categories WHERE path = 'man'), 'trousers', 'TROUSERS', 'man/trousers', 7),
  ((SELECT id FROM categories WHERE path = 'man'), 'jeans', 'JEANS', 'man/jeans', 8),
  ((SELECT id FROM categories WHERE path = 'man'), 'shoes', 'SHOES', 'man/shoes', 9),
  ((SELECT id FROM categories WHERE path = 'man'), 'bags', 'BAGS', 'man/bags', 10),
  ((SELECT id FROM categories WHERE path = 'man'), 'accessories', 'ACCESSORIES', 'man/accessories', 11),
  ((SELECT id FROM categories WHERE path = 'man'), 'perfumes', 'PERFUMES', 'man/perfumes', 12),
  ((SELECT id FROM categories WHERE path = 'kids'), 'girl', 'GIRL | 6-14 YEARS', 'kids/girl', 0),
  ((SELECT id FROM categories WHERE path = 'kids'), 'boy', 'BOY | 6-14 YEARS', 'kids/boy', 1),
  ((SELECT id FROM categories WHERE path = 'kids'), 'baby-girl', 'BABY GIRL | 3 MONTHS-4 YEARS', 'kids/baby-girl', 2),
  ((SELECT id FROM categories WHERE path = 'kids'), 'baby-boy', 'BABY BOY | 3 MONTHS-4 YEARS', 'kids/baby-boy', 3),
  ((SELECT id FROM categories WHERE path = 'kids'), 'shoes', 'SHOES', 'kids/shoes', 4),
  ((SELECT id FROM categories WHERE path = 'kids'), 'accessories', 'ACCESSORIES', 'kids/accessories', 5)
ON CONFLICT (path) DO NOTHING;
